version: '3.8'

services:
  backend:
    build: ./backend
    container_name: shield-metrics-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - shield-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: shield-metrics-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - shield-network

networks:
  shield-network:
    driver: bridge